CREATE TABLE admin_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100)  NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,
    display_name  VARCHAR(150)  NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP     NOT NULL
);

CREATE TABLE refresh_token (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT        NOT NULL REFERENCES admin_user(id),
    token_hash    VARCHAR(128)  NOT NULL UNIQUE,
    expires_at    TIMESTAMP     NOT NULL,
    revoked       BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP     NOT NULL
);
CREATE INDEX idx_refresh_token_admin_user ON refresh_token(admin_user_id);

CREATE TABLE category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(120) NOT NULL UNIQUE,
    name       VARCHAR(150) NOT NULL,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL
);

CREATE TABLE item (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              VARCHAR(160)  NOT NULL UNIQUE,
    title             VARCHAR(200)  NOT NULL,
    theme_description VARCHAR(500),
    category_id       BIGINT        NOT NULL REFERENCES category(id),
    image_url         VARCHAR(1000),
    image_alt         VARCHAR(300),
    s3_key            VARCHAR(500),
    category_tone     VARCHAR(30)   NOT NULL DEFAULT 'gold',
    swatch_color      VARCHAR(40),
    coming_soon       BOOLEAN       NOT NULL DEFAULT FALSE,
    published         BOOLEAN       NOT NULL DEFAULT TRUE,
    sort_order        INTEGER       NOT NULL DEFAULT 0,
    created_at        TIMESTAMP     NOT NULL,
    updated_at        TIMESTAMP     NOT NULL
);
CREATE INDEX idx_item_category ON item(category_id);

CREATE TABLE lookbook_slide (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url  VARCHAR(1000) NOT NULL,
    image_alt  VARCHAR(300),
    s3_key     VARCHAR(500),
    eyebrow    VARCHAR(120),
    caption    VARCHAR(300),
    sort_order INTEGER       NOT NULL DEFAULT 0,
    created_at TIMESTAMP     NOT NULL,
    updated_at TIMESTAMP     NOT NULL
);

CREATE TABLE site_content (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_key   VARCHAR(120)  NOT NULL UNIQUE,
    content_value TEXT          NOT NULL,
    label         VARCHAR(150)  NOT NULL,
    content_group VARCHAR(50)   NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP     NOT NULL
);

CREATE TABLE newsletter_subscriber (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    source     VARCHAR(100),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL
);
